[theme]
base                     = "dark"
primaryColor             = "#ffffff"
backgroundColor          = "#000000"
secondaryBackgroundColor = "#000000"
textColor                = "#f1f5f9"
font                     = "sans serif"
