[theme]
base                     = "dark"
primaryColor             = "#ECE9E3"
backgroundColor          = "#070707"
secondaryBackgroundColor = "#0E0E0D"
textColor                = "#ECE9E3"
font                     = "sans serif"
